name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: CGO_ENABLED="0" GOOS=linux GOARCH=amd64 go build -o gclip ./internal/*.go &&  gzip -f gclip

    - name: Test
      run: sudo apt install -y libx11-dev && sudo apt install -y xvfb && Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & export DISPLAY=:99.0 && go test -v ./...

    - name: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: gclip
        tag_name: 0.9.2
#        body_path: CHANGELOG.md

    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: gclip.tar.gz
        asset_name: gclip.tar.gz
        asset_content_type: application/gzip