name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Deps
      run: sudo apt install -y libx11-dev && sudo apt install -y xvfb

    - name: Build
      run: CGO_ENABLED="0" GOOS=linux GOARCH=amd64 go build -o gclip ./internal/*.go

    - name: Test
      run: sudo apt install -y libx11-dev && sudo apt install -y xvfb && go test -v ./...
